logging:
  level: 
    com.bcc.security.admin: INFO
spring:
  application:
    name: ace-admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/ag_admin?useUnicode=true&characterEncoding=UTF8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  basepackage: com.bcc.security.admin.mapper
  xmlLocation: classpath:mapper/**/*.xml

server:
    port: 8762

eureka:
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

swagger:
    basepackage: com.bcc.security.admin
    service:
        name: BCC
        description: BCC 后端服务
auth:
  serviceId: ace-auth
  user:
    token-header: Authorization

#redis-cache 相关
redis: 
  pool:
    maxActive: 300
    maxIdle: 100
    maxWait: 1000
  host: 192.168.20.208
  port: 6379
  password:
  timeout: 2000
  sysName: ace-admin
  enable: true
  database: 0